Reuzze\ReuzzeBundle\Entity\Categories:
    type: entity
    table: categories
    indexes:
        fk_categories_categories1_idx:
            columns:
                - category_parentid
    id:
        categoryId:
            type: boolean
            nullable: false
            comment: ''
            id: true
            column: category_id
            generator:
                strategy: IDENTITY
    fields:
        categoryName:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: category_name
        categoryDescription:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: category_description
        categoryCreated:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: category_created
        categoryModified:
            type: datetime
            nullable: true
            comment: ''
            column: category_modified
        categoryDeleted:
            type: datetime
            nullable: true
            comment: ''
            column: category_deleted
    manyToOne:
        categoryParentid:
            targetEntity: Categories
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_parentid:
                    referencedColumnName: category_id
            orphanRemoval: false
    manyToMany:
        entity:
            targetEntity: Entities
            cascade: {  }
            mappedBy: category
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
