Reuzze\ReuzzeBundle\Entity\Entities:
    type: entity
    table: entities
    indexes:
        fk_entities_users1:
            columns:
                - user_id
        fk_entities_countries1_idx:
            columns:
                - region_id
    id:
        entityId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: entity_id
            generator:
                strategy: IDENTITY
    fields:
        entityTitle:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: entity_title
        entityDescription:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: entity_description
        entityStarttime:
            type: datetime
            nullable: false
            comment: ''
            column: entity_starttime
        entityEndtime:
            type: datetime
            nullable: false
            comment: ''
            column: entity_endtime
        entityType:
            type: string
            nullable: false
            length: 16
            fixed: false
            comment: ''
            column: entity_type
        entityInstantsellingprice:
            type: decimal
            nullable: false
            precision: 12
            scale: 2
            comment: ''
            column: entity_instantsellingprice
        entityShippingprice:
            type: decimal
            nullable: true
            precision: 6
            scale: 2
            comment: ''
            column: entity_shippingprice
        entityCondition:
            type: string
            nullable: false
            length: 16
            fixed: false
            comment: ''
            column: entity_condition
        entityViews:
            type: bigint
            nullable: true
            unsigned: false
            comment: ''
            column: entity_views
        entityCreated:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: entity_created
        entityModified:
            type: datetime
            nullable: true
            comment: ''
            column: entity_modified
        entityDeleted:
            type: datetime
            nullable: true
            comment: ''
            column: entity_deleted
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
        region:
            targetEntity: Regions
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                region_id:
                    referencedColumnName: region_id
            orphanRemoval: false
    manyToMany:
        category:
            targetEntity: Categories
            cascade: {  }
            mappedBy: null
            inversedBy: entity
            joinTable:
                name: entities_has_categories
                joinColumns:
                    -
                        name: entity_id
                        referencedColumnName: entity_id
                inverseJoinColumns:
                    -
                        name: category_id
                        referencedColumnName: category_id
            orderBy: null
    lifecycleCallbacks: {  }
