Reuzze\ReuzzeBundle\Entity\Media:
    type: entity
    table: media
    id: {  }
    fields:
        mediumId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: medium_id
            generator:
                strategy: IDENTITY
        mediumUrl:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: medium_url
        mediumType:
            type: string
            nullable: false
            length: 3
            fixed: true
            comment: ''
            default: GNR
            column: medium_type
        mediumMimetype:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: medium_mimetype
        mediumIsexternal:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: medium_isexternal
    oneToOne:
        medium:
            targetEntity: Entities
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                medium_id:
                    referencedColumnName: entity_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
