Reuzze\ReuzzeBundle\Entity\Persons:
    type: entity
    table: persons
    indexes:
        fk_persons_addresses1_idx:
            columns:
                - address_id
    id:
        personId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: person_id
            generator:
                strategy: IDENTITY
    fields:
        personFirstname:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: person_firstname
        personSurname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: person_surname
        personProfile:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: person_profile
        personCreated:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: person_created
        personModified:
            type: datetime
            nullable: true
            comment: ''
            column: person_modified
        personDeleted:
            type: datetime
            nullable: true
            comment: ''
            column: person_deleted
    manyToOne:
        address:
            targetEntity: Addresses
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                address_id:
                    referencedColumnName: address_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
