Reuzze\ReuzzeBundle\Entity\Regions:
    type: entity
    table: regions
    id:
        regionId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: region_id
            generator:
                strategy: IDENTITY
    fields:
        regionName:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: region_name
    lifecycleCallbacks: {  }
