Reuzze\ReuzzeBundle\Entity\Users:
    type: entity
    table: users
    indexes:
        fk_users_persons1:
            columns:
                - person_id
        fk_users_languages1_idx:
            columns:
                - language_id
    uniqueConstraints:
        user_username_UNIQUE:
            columns:
                - user_username
        user_email_UNIQUE:
            columns:
                - user_email
    id:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: user_id
    fields:
        userUsername:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: user_username
        userEmail:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: user_email
        userRating:
            type: decimal
            nullable: false
            precision: 2
            scale: 0
            comment: ''
            default: '10'
            column: user_rating
        userCreated:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: user_created
        userModified:
            type: datetime
            nullable: true
            comment: ''
            column: user_modified
        userDeleted:
            type: datetime
            nullable: true
            comment: ''
            column: user_deleted
        userLastlogin:
            type: datetime
            nullable: true
            comment: ''
            column: user_lastlogin
        userLocked:
            type: datetime
            nullable: true
            comment: ''
            column: user_locked
    oneToOne:
        person:
            targetEntity: Persons
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                person_id:
                    referencedColumnName: person_id
            orphanRemoval: false
        language:
            targetEntity: Languages
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                language_id:
                    referencedColumnName: language_id
            orphanRemoval: false
    manyToMany:
        role:
            targetEntity: Roles
            cascade: {  }
            mappedBy: null
            inversedBy: user
            joinTable:
                name: users_has_roles
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: user_id
                inverseJoinColumns:
                    -
                        name: role_id
                        referencedColumnName: role_id
            orderBy: null
    lifecycleCallbacks: {  }
